name: ✨ Feature Request
description: Suggest a new feature for the Quiz System
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # ✨ Feature Request for Quiz System
        
        We love hearing new ideas! Help us make the Quiz System even better for teachers and students.
        
        **Educational Focus**: Remember that this tool is designed for educational use, so features should enhance the teaching and learning experience.

  - type: textarea
    id: feature-summary
    attributes:
      label: 🎯 Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: 📍 Feature Area
      description: Which part of the Quiz System would this feature affect?
      options:
        - Quiz Generator (Teacher Interface)
        - Quiz Test Runner (Student Interface)
        - Rich Text Editor (Mathematical Formulas)
        - Question Types (Multiple Choice, True/False)
        - Image Support
        - Import/Export Features
        - Mobile Experience
        - Testing & Quality Assurance
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-solving
    attributes:
      label: 🔍 Problem This Solves
      description: What problem would this feature solve? What pain point does it address?
      placeholder: "Currently, teachers have difficulty with... This feature would solve that by..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        I think we could add...
        
        The feature would work like this:
        1. User clicks...
        2. System displays...
        3. User can then...
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: 👤 User Story
      description: Describe this feature from a user's perspective
      placeholder: |
        As a [teacher/student/administrator],
        I want to [action],
        So that I can [benefit/goal].
        
        Example: "As a chemistry teacher, I want to create chemical reaction equations with arrows and multiple steps, so that I can test students on complex chemical processes."

  - type: checkboxes
    id: educational-benefits
    attributes:
      label: 🎓 Educational Benefits
      description: What educational benefits would this feature provide? (Check all that apply)
      options:
        - label: Improves accessibility for students with disabilities
        - label: Supports different learning styles (visual, auditory, kinesthetic)
        - label: Enhances engagement and motivation
        - label: Provides better assessment capabilities
        - label: Saves teachers time in quiz creation
        - label: Improves student understanding of concepts
        - label: Supports collaborative learning
        - label: Enables personalized learning paths
        - label: Provides better analytics/insights
        - label: Supports multiple languages or internationalization

  - type: dropdown
    id: target-users
    attributes:
      label: 👥 Primary Target Users
      description: Who would benefit most from this feature?
      options:
        - Teachers (Quiz Creators)
        - Students (Quiz Takers)
        - Administrators
        - All Users
        - Developers/Contributors
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Have you considered alternative solutions? What other approaches might work?
      placeholder: "I also considered... but this wouldn't work because..."

  - type: textarea
    id: use-cases
    attributes:
      label: 🎯 Use Cases & Examples
      description: Provide specific examples of how this feature would be used
      placeholder: |
        Example 1: Math teacher creating calculus problems with complex equations
        Example 2: Science teacher adding interactive molecular diagrams
        Example 3: History teacher incorporating timeline visualizations

  - type: checkboxes
    id: rich-text-related
    attributes:
      label: 🧮 Rich Text & Formula Related
      description: If this feature involves rich text or mathematical formulas, check relevant areas
      options:
        - label: Advanced mathematical notation (beyond current H₂O, E=mc²)
        - label: LaTeX support for complex equations
        - label: Chemical reaction arrows and multi-step processes
        - label: Geometric shapes and diagrams
        - label: Graph plotting capabilities
        - label: Scientific notation enhancements
        - label: Programming code syntax highlighting
        - label: Music notation support

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority Level
      description: How important is this feature to you?
      options:
        - Nice to have (Low priority)
        - Would be useful (Medium priority)
        - Important for my workflow (High priority)
        - Essential for my teaching (Critical priority)
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: ⚙️ Implementation Complexity (Your Estimate)
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (Small UI change or minor feature)
        - Moderate (New functionality, some backend work)
        - Complex (Major feature, significant development)
        - Very Complex (Architectural changes, extensive testing)
        - I'm not sure

  - type: textarea
    id: technical-considerations
    attributes:
      label: 🔧 Technical Considerations
      description: Any technical aspects to consider? (Optional - only if you have technical knowledge)
      placeholder: |
        - Browser compatibility concerns?
        - Mobile device considerations?
        - Offline functionality requirements?
        - Performance implications?
        - Security considerations?
        - Integration with existing features?

  - type: checkboxes
    id: compatibility
    attributes:
      label: 🌐 Compatibility Requirements
      description: What compatibility should this feature maintain?
      options:
        - label: Must work offline (no internet required)
        - label: Must work on all supported browsers (Chrome, Firefox, Safari, Edge)
        - label: Must work on mobile devices (tablets, phones)
        - label: Must maintain backward compatibility with existing quizzes
        - label: Must preserve rich text formatting (H₂O, E=mc²)
        - label: Must integrate with current testing framework (210 tests)

  - type: textarea
    id: mockups
    attributes:
      label: 🎨 Mockups or Visual Examples
      description: Do you have any wireframes, mockups, or examples from other tools?
      placeholder: |
        Share any visual references:
        - Screenshots from other tools
        - Hand-drawn sketches
        - Wireframes or mockups
        - Links to similar features elsewhere

  - type: textarea
    id: success-criteria
    attributes:
      label: ✅ Success Criteria
      description: How would we know this feature is successful? What would success look like?
      placeholder: |
        This feature would be successful if:
        - Teachers can create [specific type] of quizzes in under [time]
        - Students report improved understanding of [subject]
        - The feature is used by X% of users within [timeframe]
        - No significant performance impact on quiz loading

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 🎯 Current Quiz System Capabilities
        
        **Rich Text**: Mathematical formulas (H₂O, E=mc²), subscripts, superscripts, bold, italic, underline  
        **Question Types**: Multiple choice (2-6 options), True/False  
        **Browsers**: Chrome, Firefox, Safari, Edge (full offline support)  
        **Mobile**: Responsive design for tablets and phones  
        **Images**: Upload and display in questions  
        **Export**: ZIP packages and JSON formats  
        **Testing**: 210 automated tests ensure quality  
        
        **Contributing**: If you're interested in implementing this feature, check our [contribution guidelines](https://github.com/anbanm/quiz-system#contributing)!
        
        Thank you for helping us improve education technology! 🚀